// AUTOGENERATED FILE FROM MARKDOWN. DO NOT EDIT.
export const MERMAID_RULES_3 = `
## 3. Security and Interaction Directives

### 3.1 Security Level (\`securityLevel\`)
This configuration property governs the trust level for parsed diagrams, impacting content processing and interactivity.
*   \`'strict'\` (default): HTML tags are encoded, and click functionality (interaction, actor menus) is disabled.
*   \`'antiscript'\`: HTML tags are permitted (scripts removed), and click functionality is enabled.
*   \`'loose'\`: HTML tags are permitted, and click functionality is enabled.
*   \`'sandbox'\`: Rendering occurs within a sandboxed iframe, preventing JavaScript execution but potentially hindering interactive features. Source security is the site owner's responsibility when \`securityLevel\` is not \`strict\`.

### 3.2 Configuration Access and Mutability
*   Configurations provided via \`init\` directives cannot alter parameters specified in a higher-level \`secure\` array. Mermaid prioritizes \`secure\` array values in case of collision.
*   The \`secure\` array defines parameters immutable by \`init\` directives. Default immutable values: \`'secure'\`, \`'securityLevel'\`, \`'startOnLoad'\`, \`'maxTextSize'\`.
*   Site owners can extend the \`secure\` array using \`mermaidAPI.initialize({..., secure: ['parameter1', 'parameter2']})\`.
*   \`setSiteConfig\` values must exclude those in the \`secure\` array.
*   \`setConfig\` parameters are sanitized against \`siteConfig.secure\` keys; conflicting values are replaced by \`siteConfig\` values.
*   \`reset()\` and \`globalReset()\` functions are restricted to site owners.
*   \`sanitize(options)\` modifies options in-place to prevent overriding \`siteConfig\` secure keys.

### 3.3 Click Event Binding
*   **JavaScript Callback:**
    *   Syntax: \`click <nodeId> <callbackFunctionName>\` or \`click <nodeId> call <callbackFunctionName>()\`.
    *   The \`callbackFunctionName\` must be a JavaScript function defined on the page. It receives \`nodeId\` (or \`taskId\` for Gantt) as a parameter unless other arguments are explicitly specified for Gantt.
*   **URL Navigation:**
    *   Syntax: \`click <nodeId> "<url>"\` or \`click <nodeId> href "<url>"\`.
    *   Links default to opening in the same tab/window. Specify a link target (e.g., \`_self\`, \`_blank\`) within the click definition to alter this behavior.
*   **Tooltips:** Enclose tooltip text in double quotes.

### 3.4 Actor Menus (Sequence Diagrams)
*   **Simple Menu:** \`link <actor>: <link-label> @ <link-url>\`.
*   **Advanced JSON Menu:** \`links <actor>: {"<link-name>": "<link-url>", ...}\`.
`;
