// AUTOGENERATED FILE FROM MARKDOWN. DO NOT EDIT.
export const MERMAID_RULES_1 = `
# Rewritten Narrative Report

**Generated on:** September 14, 2025 at 1:14 AM CDT

---

## Generated Narrative

This document establishes the definitive technical rules, syntax requirements, and constraints governing the Mermaid diagramming platform. Adherence to these mandates ensures precise rendering, consistent functionality, and effective validation across all Mermaid implementations.

---

## 1. Core Principles and Operational Requirements

### 1.1 General Principles
*   Files explicitly marked "AUTOGENERATED FILE. DO NOT EDIT." must not be modified directly. Source files require alteration.
*   Experimental diagram types and features (e.g., C4, Mindmap, Sankey, Timeline, Treemap, ZenUML, Radar, Architecture, Packet diagrams) exhibit syntax and properties subject to modification in future releases.
*   Mermaid does not support the Internet Explorer browser.

### 1.2 System and Environment Requirements for Rendering
*   **Node.js:** Installation of Node.js version 16 or newer is required for local rendering and validation.
*   **PNPM:** Installation of the \`pnpm\` package manager is required. Execute \`pnpm env use --global 20\` and reload shell configuration post-setup.
*   **Docker:** For Docker-based rendering, ensure Docker is installed. An X11 server must be operational on the host for GUI applications (e.g., Cypress) within Docker. Verify with \`echo $DISPLAY\`.
*   **Font Handling:** Mermaid necessitates complete page loading (DOM + assets, particularly font files) prior to rendering diagrams utilizing dynamically loaded CSS fonts. This prevents label misplacement. Specify fonts for \`.mermaid\` elements (e.g., \`pre.mermaid { font-family: 'trebuchet ms', verdana, arial; }\`) to ensure correct application.
*   **KaTeX/MathML:** External KaTeX stylesheets are mandatory when \`legacyMathML\` is enabled or for general MathML rendering.
*   **External Integrations:**
    *   **FontAwesome:** Integrate FontAwesome CSS on the host website or register icon packs via the Mermaid API for icon support.
    *   **ELK Layout:** For ELK layout application (e.g., ER Diagrams, Flowcharts), Mermaid version 9.4+ is required, with the ELK layout/renderer feature enabled in the lazy-loading configuration.
*   **Bug Fixes:** For resolution of actor/participant creation/deletion errors in Sequence diagrams, deploy Mermaid v10.7.0+.
`;
