// AUTOGENERATED FILE FROM MARKDOWN. DO NOT EDIT.
export const MERMAID_RULES_7 = `
## 7. File Management Directives
*   Applications supporting Mermaid files *should* use \`.mermaid\` or \`.mmd\` file extensions.
*   The recommended MIME type for Mermaid media is \`text/vnd.mermaid\`.
`;
